language: node_js
node_js:
- lts/*
deploy:
  skip_cleanup: true
  provider: npm
  email: koutnypetr@seznam.cz
  api_key:
    secure: wZx1FMRIp+mDrnnXmHODoS9uTa9SNHEIk9Z3eTgsXc55Y89S149nSV+PGtWI16+bGFTd6IeYsSI7LT13zoZuKcgC2cCclxWaY1eXo+2u4xrhuCj8k2J3hODt4DEZRPy4TC6bO1knphpRi3PBo3My9wX2rRvRgSrPFzw3YtpPBeSnejt43Tf5VKnNsl/cSUM86Oko+WIZbmpMh1+WX8oNpNQGqndwE6rKpmnQvA9LzAIA2uYCJn+J5hZncFPmADA+or+Uwef1QRSzIdwonYikWBVlcnGWC1GURGgXPng+abwlsBgOYXEkYH41tFfLPUUqsQ2/zgOQqhbfw3yj72rFjB41TpsVy/xvUstf1Cq0f2lniSYwQejswwY3mGDv2OCVlUaPeG3IWvnaM8GlVWOcYDKNKvykm/dTXBVoc2U1UglNRTQiJ2vQoW7gdSiZFEFrpTfblWGj7qHcumGIWNmM6oGyTE5/hrD4A0w+6EsP80+evCQK+ceDkvuGR9pJpBdVEdzA9KUzV/RXhLk/aZ4PgiOCkHsSxkfVvUWSr/6/ej3fWzPBA+C3vtF90xiGCgP4yl9J+VkfrO9CM8cRGmNbM3XmzDtpnFyQHw8th4mmy6qCS2IMgDTZuRhPPJ1/aNnOjZ+sGw2W42YZbGsTFo4dwjpTGJeWsReITlk7KAwOZdw=
  on:
    branch: master
