language: node_js
node_js:
- lts/*
deploy:
  skip_cleanup: true
  provider: npm
  email: koutnypetr@seznam.cz
  api_key:
    secure: XWUrP1AbtekZy03aJFG7nqte14IsSadpjBCJMOPB31TIGBWimyY5MH2D2+/OmqNXiFYALg3dZM9Ws7Qgy3I8fTD8AI/+9aIIyoOtTQ1bgryRQeji5yxrR3yi4Onn1vl9ugoHnnemAUQY4yzC6FwjdxBRlQJKTkim/xvUII0dRovGIa2bcWnp60rv+QoeWmNp7CvW1/302ETe5MpiDLyb5YSZWQIuZ+u8Bv1FpIfyW3L5bM1JaoUcUf0opwzYe6Chnz64AFPtyW7cTCz3RDyYV4pnvvU+T/iv1zGgyw8fkr8jyB8biqj0/zjkAkT4DDESCn5rdw/BMH87noq8ajmUf9EeONSGSmjAXscrbQpCafDqhMMtkTA7qyhYqo6hdtOKDexOirxakVLUrfXtj9rMCBqDfdtZQIc3n+WcsHdK30PWdp0JM4fcoq0RdyeTpa3F3nohtGEqU+O0Eq+Mgf46dEsIC4ZMVsffnuu4yZ01zeq/YdotnAL0+0fZO9KPQuKjM9s5VVEJyaeZ0aUCoLZxO/jBtzdhcl4sxJR/hnZxzmU89KcyxyRDUd5kLtbJfm5fkzJ1WFWuXNt4bF7KxbMtFjd2oJCUEaSvxOyUYrTGsuTxZ+lxDDU8Lt/iEIbvSHlJ3oz+DmOoeoZeXj6p5oHpHnxYIZSm/2oY5LoLR9pbqtY=
  on:
    branch: master
